### PR TITLE
Outside cyk open m pcheckpoint

### PR DESCRIPTION
**Pull request by sjanssen2**

### CODE REVIEW

**Comment by fymue** [comment]
Hi @sjanssen2,

i think i was able to fix the checkpointing issues for `outside` + `OpenMP` + `cyk` - style programs. 
As far as I can tell, you actually implemented all of the index archiving/updating for the checkpointing in the new parallel `outside` loops correctly. There were just some other minor bugs that caused some issues. With the latest commit, I fixed the following 3 bugs:

- the `t_0_i_outside` loop variable in the single-threaded cyk loops was not tracked during checkpointing; I added it to the loop variables we archive/load
- the update of the `outer_loop_1_idx` in the first parallel cyk loop was incorrect; it used to just re-execute the following statement: `outer_loop_1_idx = (outer_loop_1_idx_start + tile_size);`, which doesn't do anything meaningful since `outer_loop_1_idx_start` is only meant to serve as the starting index for the outer loop idx and isn't adjusted at any point; instead, `outer_loop_1_idx`should be incremented here: `outer_loop_1_idx = (outer_loop_1_idx + tile_size);`, which it now will be
- I removed the `+/-1` adjustments of some of the loop variables in `archive_cyk_indices` right before archiving, because it caused a `+1` offset bug in one of the single-threaded loops; since we lock a mutex before every loop iteration, it is ensured that no checkpoints can be dumped before the lock is free again, meaning before the current iteration ends; as a result, we don't need to do any `+/-1` calculations before archiving the loop indices to ensure the completeness of the last iteration, so I removed those

Unless I missed something, the checkpointing mechanism should now be able to correctly archive/load `outside` tables in single- and multithreaded cyk programs.

**Comment by sjanssen2** [comment]
here is a short example (note: shorter input sequences did not show this issue)
```
(base) t490s x86_64 /Daten/Git/jlab/gapc_backward>./gapc testdata/grammar_outside/nodangle.gap  --outside_grammar ALL  
(base) t490s x86_64 /Daten/Git/jlab/gapc_backward>make -f out.mf
Including global makefile /home/sjanssen/share/gapc/config_linux-gnu.mf
echo '#include "out.hh"' > out_main.cc
cat /home/sjanssen/include/rtlib/generic_main.cc >> out_main.cc
g++  -I/usr/include  -I/usr/include -I/home/sjanssen/include/ -I/home/sjanssen/include/rtlib -I/home/sjanssen/include/librna  -O3  -std=c++17 -D_XOPEN_SOURCE=500 -MMD -MP -Wall -Wnon-virtual-dtor -Wno-unused-variable -Wno-parentheses  -DNDEBUG -DBISONNEW   out_main.cc -c -o out_main.o 
g++  -I/usr/include  -I/usr/include -I/home/sjanssen/include/ -I/home/sjanssen/include/rtlib -I/home/sjanssen/include/librna  -O3  -std=c++17 -D_XOPEN_SOURCE=500 -MMD -MP -Wall -Wnon-virtual-dtor -Wno-unused-variable -Wno-parentheses  -DNDEBUG -DBISONNEW   out.cc -c -o out.o 
g++  -o out out_main.o out.o string.o  -L/usr/lib/x86_64-linux-gnu  -L/home/sjanssen/lib/ -L/home/sjanssen/lib/rtlib -L/home/sjanssen/lib/librna   -Xlinker -rpath -Xlinker /usr/lib/x86_64-linux-gnu      -Xlinker -rpath -Xlinker /home/sjanssen/lib/ -Xlinker -rpath -Xlinker /home/sjanssen/lib/rtlib -Xlinker -rpath -Xlinker /home/sjanssen/lib/librna    -L/usr/lib/x86_64-linux-gnu -lgsl -lgslcblas -lm -lrna 
(base) t490s x86_64 /Daten/Git/jlab/gapc_backward>mv out out_unger_nocp
(base) t490s x86_64 /Daten/Git/jlab/gapc_backward>./gapc testdata/grammar_outside/nodangle.gap  --outside_grammar ALL  --checkpoint
(base) t490s x86_64 /Daten/Git/jlab/gapc_backward>make -f out.mf
Including global makefile /home/sjanssen/share/gapc/config_linux-gnu.mf
echo '#include "out.hh"' > out_main.cc
cat /home/sjanssen/include/rtlib/generic_main.cc >> out_main.cc
g++  -I/usr/include  -I/usr/include -I/home/sjanssen/include/ -I/home/sjanssen/include/rtlib -I/home/sjanssen/include/librna  -O3  -std=c++17 -D_XOPEN_SOURCE=500 -MMD -MP -Wall -Wnon-virtual-dtor -Wno-unused-variable -Wno-parentheses  -DNDEBUG -DBISONNEW   out_main.cc -c -o out_main.o 
g++  -I/usr/include  -I/usr/include -I/home/sjanssen/include/ -I/home/sjanssen/include/rtlib -I/home/sjanssen/include/librna  -O3  -std=c++17 -D_XOPEN_SOURCE=500 -MMD -MP -Wall -Wnon-virtual-dtor -Wno-unused-variable -Wno-parentheses  -DNDEBUG -DBISONNEW   out.cc -c -o out.o 
g++  -o out out_main.o out.o string.o  -L/usr/lib/x86_64-linux-gnu  -L/home/sjanssen/lib/ -L/home/sjanssen/lib/rtlib -L/home/sjanssen/lib/librna   -Xlinker -rpath -Xlinker /usr/lib/x86_64-linux-gnu      -Xlinker -rpath -Xlinker /home/sjanssen/lib/ -Xlinker -rpath -Xlinker /home/sjanssen/lib/rtlib -Xlinker -rpath -Xlinker /home/sjanssen/lib/librna    -L/usr/lib/x86_64-linux-gnu -lgsl -lgslcblas -lm -lrna  -lboost_serialization -lboost_filesystem -lpthread -ldl

(base) t490s x86_64 /Daten/Git/jlab/gapc_backward>seq=uaucgguacuacgugacguugacguguaucgguacuacgugaacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacguga; ./out_unger_nocp $seq > o_nocp; ./out $seq -p 0:0:0:1 > o_cp; diff o_nocp o_cp; echo $?
Checkpointing routine has been integrated. A new checkpoint will be created every 0 days, 0 hours, 0 minutes and 1 seconds.
The checkpoints will be saved at "/Daten/Git/jlab/gapc_backward".

Info: Archived "dangle_table" table into "/Daten/Git/jlab/gapc_backward/out_78750_dangle_table". Table is 95.19% filled.
Info: Archived "iloop_table" table into "/Daten/Git/jlab/gapc_backward/out_78750_iloop_table". Table is 91.43% filled.
Info: Archived "ml_comps_table" table into "/Daten/Git/jlab/gapc_backward/out_78750_ml_comps_table". Table is 87.70% filled.
Info: Archived "ml_comps1_table" table into "/Daten/Git/jlab/gapc_backward/out_78750_ml_comps1_table". Table is 95.12% filled.
Info: Archived "outside_dangle_table" table into "/Daten/Git/jlab/gapc_backward/out_78750_outside_dangle_table". Table is 100.00% filled.
Info: Archived "outside_iloop_table" table into "/Daten/Git/jlab/gapc_backward/out_78750_outside_iloop_table". Table is 37.18% filled.
Info: Archived "outside_ml_comps_table" table into "/Daten/Git/jlab/gapc_backward/out_78750_outside_ml_comps_table". Table is 90.50% filled.
Info: Archived "outside_ml_comps1_table" table into "/Daten/Git/jlab/gapc_backward/out_78750_outside_ml_comps1_table". Table is 95.19% filled.
Info: Archived "outside_strong_table" table into "/Daten/Git/jlab/gapc_backward/out_78750_outside_strong_table". Table is 82.32% filled.
Info: Archived "outside_struct_table" table into "/Daten/Git/jlab/gapc_backward/out_78750_outside_struct_table". Table is 100.00% filled.
Info: Archived "outside_weak_table" table into "/Daten/Git/jlab/gapc_backward/out_78750_outside_weak_table". Table is 38.35% filled.
Info: Archived "strong_table" table into "/Daten/Git/jlab/gapc_backward/out_78750_strong_table". Table is 95.19% filled.
Info: Archived "struct_table" table into "/Daten/Git/jlab/gapc_backward/out_78750_struct_table". Table is 100.00% filled.
Info: Archived "weak_table" table into "/Daten/Git/jlab/gapc_backward/out_78750_weak_table". Table is 95.19% filled.
363074,363076d363073
< -10710
< //end answers outside_strong(99,104)
< start answers outside_strong(99,105):
363091,363092c363088
< start answers outside_strong(99,110):
< -9350
---
> start answers outside_strong(99,-9350
363112,363116c363108
< start answers outside_strong(99,117):
< -8460
< //end answers outside_strong(99,117)
< start answers outside_strong(99,118):
< -8370
---
> start answers outside_strong(99-8370
363356,363358d363347
< -5240
< //end answers outside_strong(99,198)
< start answers outside_strong(99,199):
363361,363362c363350
< start answers outside_strong(99,200):
< -4710
---
> start answers outside_strong(99,-4710
1
```

**Comment by sjanssen2** [comment]
could this last issue be caused by some wired stream operations in the generated `report_insideoutside` function?

**Comment by fymue** [comment]
> could this last issue be caused by some wired stream operations in the generated `report_insideoutside` function?

Could be, yes. Looks like something is getting mixed up. Will take a look

**Comment by fymue** [comment]
Just got done doing some testing:

- I compiled a reference program and created some reference output:
```
gapc --outside_grammar ALL -o ref.cc testdata/grammar_outside/nodangle.gap
make -f ref.mf
./ref guugacguguacagucguagucguagucguaguaucgguacuacgugaacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacuaucgguacuacgugacguugacguguaucgguacuacgugaacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguagucguagcuguacgagggcuagucguagucugagucguagcugugucguagucguaucacuac > correct.txt
```
- I then compared that reference output to the output of a single-/multithreaded cyk version of the same program: 
```
gapc --outside_grammar ALL --cyk -o ref_cyk.cc testdata/grammar_outside/nodangle.gap
make -f ref_cyk.mf
./ref_cyk guugacguguacagucguagucguagucguaguaucgguacuacgugaacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacuaucgguacuacgugacguugacguguaucgguacuacgugaacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguagucguagcuguacgagggcuagucguagucugagucguagcugugucguagucguaucacuac > cmp_1.txt
```
and
```
gapc --outside_grammar ALL --cyk -o ref_cyk_parallel.cc testdata/grammar_outside/nodangle.gap
CPPFLAGS="-fopenmp" make -f ref_cyk_parallel.mf
./ref_cyk_parallel guugacguguacagucguagucguagucguaguaucgguacuacgugaacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacuaucgguacuacgugacguugacguguaucgguacuacgugaacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguagucguagcuguacgagggcuagucguagucugagucguagcugugucguagucguaucacuac > cmp_2.txt
```

There was no diff between the outputs stored in `correct.txt` and `cmp_1.txt` or `cmp_2.txt`; just like in your tests.

I then tested the same programs with the checkpointing mechanism activated:

Unger style:
```
gapc --outside_grammar ALL --checkpoint -o cp_regular.cc testdata/grammar_outside/nodangle.gap
make -f cp_regular.mf
./cp_regular guugacguguacagucguagucguagucguaguaucgguacuacgugaacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacuaucgguacuacgugacguugacguguaucgguacuacgugaacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguagucguagcuguacgagggcuagucguagucugagucguagcugugucguagucguaucacuac > cmp_3.txt
```
Single-threaded cyk style:
```
gapc --outside_grammar ALL --checkpoint -o cp_cyk.cc testdata/grammar_outside/nodangle.gap
make -f cp_cyk.mf
./cp_cyk guugacguguacagucguagucguagucguaguaucgguacuacgugaacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacuaucgguacuacgugacguugacguguaucgguacuacgugaacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguagucguagcuguacgagggcuagucguagucugagucguagcugugucguagucguaucacuac > cmp_4.txt
```
And multi-threaded cyk style:
```
gapc --outside_grammar ALL --checkpoint -o cp_cyk_parallel.cc testdata/grammar_outside/nodangle.gap
make -f cp_cyk_parallel.mf
./cp_cyk_parallel guugacguguacagucguagucguagucguaguaucgguacuacgugaacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacuaucgguacuacgugacguugacguguaucgguacuacgugaacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguagucguagcuguacgagggcuagucguagucugagucguagcugugucguagucguaucacuac > cmp_5.txt
```

Again, there was no diff between the outputs stored in `correct.txt` and `cmp_3.txt`,  `cmp_4.txt` or  `cmp_5.txt`. I also created some checkpoints before the outside phase and reloaded all versions (unger style and single-/multi-threaded cyk) from those checkpoints; still got the same output. I also created some checkpoints during the outside phase in all versions, reloaded from those and once again got the same output. 

This is weird, because you mentioned that your checkpointed programs produce incorrect output, while mine don't. What do we make of this?

**Comment by sjanssen2** [comment]
thanks for looking into this issue @fymue 
It is really weird that is does not reproduce on your end. I now re-executed the same steps not on my laptop but on one of the machines of the BCF. Results (i.e. output is not equal) are different, but the problem persists:
```
(base) hp-dl560 x86_64 ~/Git/jlab/gapc>./gapc testdata/grammar_outside/nodangle.gap  --outside_grammar ALL  
(base) hp-dl560 x86_64 ~/Git/jlab/gapc>make -f out.mf
Including global makefile /homes/sjanssen/share/gapc/config_linux-gnu.mf
echo '#include "out.hh"' > out_main.cc
cat /homes/sjanssen/include/rtlib/generic_main.cc >> out_main.cc
g++  -I/usr/include  -I/usr/include -I/homes/sjanssen/include/ -I/homes/sjanssen/include/rtlib -I/homes/sjanssen/include/librna  -O3  -std=c++17 -D_XOPEN_SOURCE=500 -MMD -MP -Wall -Wnon-virtual-dtor -Wno-unused-variable -Wno-parentheses -DNDEBUG -DBISONNEW   out_main.cc -c -o out_main.o 
g++  -I/usr/include  -I/usr/include -I/homes/sjanssen/include/ -I/homes/sjanssen/include/rtlib -I/homes/sjanssen/include/librna  -O3  -std=c++17 -D_XOPEN_SOURCE=500 -MMD -MP -Wall -Wnon-virtual-dtor -Wno-unused-variable -Wno-parentheses -DNDEBUG -DBISONNEW   out.cc -c -o out.o 
g++  -I/usr/include  -I/usr/include -I/homes/sjanssen/include/ -I/homes/sjanssen/include/rtlib -I/homes/sjanssen/include/librna  -O3  -std=c++17 -D_XOPEN_SOURCE=500 -MMD -MP -Wall -Wnon-virtual-dtor -Wno-unused-variable -Wno-parentheses -DNDEBUG -DBISONNEW   -c /homes/sjanssen/include/rtlib/string.cc -o string.o
g++  -o out out_main.o out.o string.o  -L/usr/lib/x86_64-linux-gnu  -L/homes/sjanssen/lib/ -L/homes/sjanssen/lib/rtlib -L/homes/sjanssen/lib/librna   -Xlinker -rpath -Xlinker /usr/lib/x86_64-linux-gnu      -Xlinker -rpath -Xlinker /homes/sjanssen/lib/ -Xlinker -rpath -Xlinker /homes/sjanssen/lib/rtlib -Xlinker -rpath -Xlinker /homes/sjanssen/lib/librna    -L/usr/lib/x86_64-linux-gnu -lgsl -lgslcblas -lm -lrna 
(base) hp-dl560 x86_64 ~/Git/jlab/gapc>mv out out_unger_nocp
(base) hp-dl560 x86_64 ~/Git/jlab/gapc>./gapc testdata/grammar_outside/nodangle.gap  --outside_grammar ALL  --checkpoint
(base) hp-dl560 x86_64 ~/Git/jlab/gapc>make -f out.mf
Including global makefile /homes/sjanssen/share/gapc/config_linux-gnu.mf
echo '#include "out.hh"' > out_main.cc
cat /homes/sjanssen/include/rtlib/generic_main.cc >> out_main.cc
g++  -I/usr/include  -I/usr/include -I/homes/sjanssen/include/ -I/homes/sjanssen/include/rtlib -I/homes/sjanssen/include/librna  -O3  -std=c++17 -D_XOPEN_SOURCE=500 -MMD -MP -Wall -Wnon-virtual-dtor -Wno-unused-variable -Wno-parentheses -DNDEBUG -DBISONNEW   out_main.cc -c -o out_main.o 
g++  -I/usr/include  -I/usr/include -I/homes/sjanssen/include/ -I/homes/sjanssen/include/rtlib -I/homes/sjanssen/include/librna  -O3  -std=c++17 -D_XOPEN_SOURCE=500 -MMD -MP -Wall -Wnon-virtual-dtor -Wno-unused-variable -Wno-parentheses -DNDEBUG -DBISONNEW   out.cc -c -o out.o 
g++  -o out out_main.o out.o string.o  -L/usr/lib/x86_64-linux-gnu  -L/homes/sjanssen/lib/ -L/homes/sjanssen/lib/rtlib -L/homes/sjanssen/lib/librna   -Xlinker -rpath -Xlinker /usr/lib/x86_64-linux-gnu      -Xlinker -rpath -Xlinker /homes/sjanssen/lib/ -Xlinker -rpath -Xlinker /homes/sjanssen/lib/rtlib -Xlinker -rpath -Xlinker /homes/sjanssen/lib/librna    -L/usr/lib/x86_64-linux-gnu -lgsl -lgslcblas -lm -lrna  -lboost_serialization -lboost_filesystem -lpthread -ldl
(base) hp-dl560 x86_64 ~/Git/jlab/gapc>seq=uaucgguacuacgugacguugacguguaucgguacuacgugaacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacguga; ./out_unger_nocp $seq > o_nocp; ./out $seq -p 0:0:0:1 > o_cp; diff o_nocp o_cp; echo $?
Checkpointing routine has been integrated. A new checkpoint will be created every 0 days, 0 hours, 0 minutes and 1 seconds.
The checkpoints will be saved at "/homes/sjanssen/Git/jlab/gapc".

Info: Archived "dangle_table" table into "/homes/sjanssen/Git/jlab/gapc/out_2699968_dangle_table". Table is 95.19% filled.
Info: Archived "iloop_table" table into "/homes/sjanssen/Git/jlab/gapc/out_2699968_iloop_table". Table is 91.43% filled.
Info: Archived "ml_comps_table" table into "/homes/sjanssen/Git/jlab/gapc/out_2699968_ml_comps_table". Table is 87.70% filled.
Info: Archived "ml_comps1_table" table into "/homes/sjanssen/Git/jlab/gapc/out_2699968_ml_comps1_table". Table is 95.12% filled.
Info: Archived "outside_dangle_table" table into "/homes/sjanssen/Git/jlab/gapc/out_2699968_outside_dangle_table". Table is 100.00% filled.
Info: Archived "outside_iloop_table" table into "/homes/sjanssen/Git/jlab/gapc/out_2699968_outside_iloop_table". Table is 36.79% filled.
Info: Archived "outside_ml_comps_table" table into "/homes/sjanssen/Git/jlab/gapc/out_2699968_outside_ml_comps_table". Table is 90.50% filled.
Info: Archived "outside_ml_comps1_table" table into "/homes/sjanssen/Git/jlab/gapc/out_2699968_outside_ml_comps1_table". Table is 95.19% filled.
Info: Archived "outside_strong_table" table into "/homes/sjanssen/Git/jlab/gapc/out_2699968_outside_strong_table". Table is 75.80% filled.
Info: Archived "outside_struct_table" table into "/homes/sjanssen/Git/jlab/gapc/out_2699968_outside_struct_table". Table is 100.00% filled.
Info: Archived "outside_weak_table" table into "/homes/sjanssen/Git/jlab/gapc/out_2699968_outside_weak_table". Table is 38.22% filled.
Info: Archived "strong_table" table into "/homes/sjanssen/Git/jlab/gapc/out_2699968_strong_table". Table is 95.19% filled.
Info: Archived "struct_table" table into "/homes/sjanssen/Git/jlab/gapc/out_2699968_struct_table". Table is 100.00% filled.
Info: Archived "weak_table" table into "/homes/sjanssen/Git/jlab/gapc/out_2699968_weak_table". Table is 95.19% filled.
351497,351502d351496
< -6880
< //end answers outside_strong(67,133)
< start answers outside_strong(67,134):
< -7040
< //end answers outside_strong(67,134)
< start answers outside_strong(67,135):
351506,351508d351499
< -6750
< //end answers outside_strong(67,136)
< start answers outside_strong(67,137):
352210,352216c352201
< start answers outside_strong(69,98):
< -7760
< //end answers outside_strong(69,98)
< start answers outside_strong(69,99):
< -7810
< //end answers outside_strong(69,99)
< start answers outside_strong(69,100):
---
> start answers outside_strong(-7760
352967,352969d352951
< -9300
< //end answers outside_strong(71,81)
< start answers outside_strong(71,82):
352971,352972d352952
< //end answers outside_strong(71,82)
< start answers outside_strong(71,83):
353783,353785d353762
< -8270
< //end answers outside_strong(73,88)
< start answers outside_strong(73,89):
354324,354326c354301
< //end answers outside_strong(74,137)
< start answers outside_strong(74,138):
< -6130
---
> //end answers outside_strong(74,-6130
354337,354341c354312
< start answers outside_strong(74,142):
< -5890
< //end answers outside_strong(74,142)
< start answers outside_strong(74,143):
< -5840
---
> start answers outside_strong(74,142-5840
354345,354346d354315
< //end answers outside_strong(74,144)
< start answers outside_strong(74,145):
355699,355700c355668
< start answers outside_strong(78,82):
< -8850
---
> start answers outside_strong(-8850
356294,356302d356261
< -5290
< //end answers outside_strong(79,154)
< start answers outside_strong(79,155):
< -5290
< //end answers outside_strong(79,155)
< start answers outside_strong(79,156):
< -5220
< //end answers outside_strong(79,156)
< start answers outside_strong(79,157):
356310,356312c356269
< //end answers outside_strong(79,159)
< start answers outside_strong(79,160):
< -4870
---
> //end answers outside_strong(-4870
356315,356317d356271
< -4870
< //end answers outside_strong(79,161)
< start answers outside_strong(79,162):
358142,358144d358095
< -5790
< //end answers outside_strong(84,155)
< start answers outside_strong(84,156):
358165,358166c358116
< start answers outside_strong(84,163):
< -5030
---
> start answers outside_strong(-5030
358880,358882d358829
< -5160
< //end answers outside_strong(86,162)
< start answers outside_strong(86,163):
358885,358889c358832
< start answers outside_strong(86,164):
< -5190
< //end answers outside_strong(86,164)
< start answers outside_strong(86,165):
< -5230
---
> start answers outside_strong(-5230
359579,359584d359521
< -5680
< //end answers outside_strong(88,160)
< start answers outside_strong(88,161):
< -5680
< //end answers outside_strong(88,161)
< start answers outside_strong(88,162):
359587,359600c359524,359525
< start answers outside_strong(88,163):
< -5570
< //end answers outside_strong(88,163)
< start answers outside_strong(88,164):
< -5610
< //end answers outside_strong(88,164)
< start answers outside_strong(88,165):
< -5700
< //end answers outside_strong(88,165)
< start answers outside_strong(88,166):
< -5670
< //end answers outside_strong(88,166)
< start answers outside_strong(88,167):
< -5380
---
> start answers outside_strong(-5610
> //end answers outside_strong(88,-5380
1
```

**Comment by sjanssen2** [comment]
your even larger sequence also produces differences in my hands, here are just the first 50 lines of the diff:
```
796757,796765d796756
< -9540
< //end answers outside_dangle(19,194)
< start answers outside_dangle(19,195):
< -9410
< //end answers outside_dangle(19,195)
< start answers outside_dangle(19,196):
< -9370
< //end answers outside_dangle(19,196)
< start answers outside_dangle(19,197):
796794,796796c796785
< //end answers outside_dangle(19,206)
< start answers outside_dangle(19,207):
< -8980
---
> //end answers outside_dangle(19,-8980
805154,805168d805142
< -6340
< //end answers outside_dangle(26,256)
< start answers outside_dangle(26,257):
< -6340
< //end answers outside_dangle(26,257)
< start answers outside_dangle(26,258):
< -6340
< //end answers outside_dangle(26,258)
< start answers outside_dangle(26,259):
< -6340
< //end answers outside_dangle(26,259)
< start answers outside_dangle(26,260):
< -6270
< //end answers outside_dangle(26,260)
< start answers outside_dangle(26,261):
805175c805149
< -6170
---
> 
805178,805180d805151
< -6170
< //end answers outside_dangle(26,264)
< start answers outside_dangle(26,265):
805197,805199c805168
< //end answers outside_dangle(26,270)
< start answers outside_dangle(26,271):
< -5140
---
> //end answers outside_dangle(-5140
805205a805175,805177
> //end answers outside_dangle(26,272)
> start answers outside_dangle(26,273):
> -5140
```

**Comment by sjanssen2** [comment]
executing the same command with my and your input in a virtual environment macOS 10.13 High Sierra leads to correct results!! Very strange.
Are we both using the same gapc code version. Mine is `4d64bc7e09d8598974ccdf42cb3dcef982de275a`, i.e. the outside_cyk_openMPcheckpoint branch.
My linux system (where it fails) is 
```
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 20.3
Release:	20.3
Codename:	una
(base) t490s x86_64 ~>uname -a
Linux t490s 5.4.0-150-generic #167-Ubuntu SMP Mon May 15 17:35:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by fymue** [comment]
Huh, that is indeed very strange. I don't know what kind of code you're referring to with `4d64bc7e09d8598974ccdf42cb3dcef982de275a`, but My GAP-C version is also based on this branch (`outside_cyk_openMPcheckpoint`). I'm on Fedora 38 (Linux Kernel version: `6.3.4-201`). My `gcc` version is `gcc (GCC) 13.1.1 20230511 (Red Hat 13.1.1-2)`.

I will re-run the same tests on our `deepgap` GPU VM, which runs on Ubuntu 20.04 with kernel version `5.4.0-146-generic` and see what the results look like on there.

**Comment by fymue** [comment]
I just r

> > I don't know what kind of code you're referring to with `4d64bc7e09d8598974ccdf42cb3dcef982de275a`
> 
> this is the hash of your last commit to this branch: [4d64bc7](https://github.com/jlab/gapc/commit/4d64bc7e09d8598974ccdf42cb3dcef982de275a)

Ah ok. Yeah that's the version I'm using as well.

I just executed the exact same tests on the `deepgap` Ubuntu VM with the latest version of this branch and got the correct results for every test. I looks like this might be an issue on your end :-/

**Comment by sjanssen2** [comment]
these files are ~36MB in size. Thus I copied them to `/vol/jlab/Scratch/` files `o_cp` and `o_nocp`.
If you work on the BCF system, you should be able to `ssh hp-dl560.internal.computational.bio.uni-giessen.de` and reproduce the issue there, as this node has Ubuntu 20.04 as OS.

**Comment by fymue** [comment]
I took at look at the files and it looks like the program that created these outputs quite literally "forgot" to print some lines of code in some places. I don't know why/how that would happen, but i looks like some strings and values aren't piped into the output stream, which causes this "output fusion" in some places. Here is an example from a side-by-side diff view:

Screenshot from 2023-06-08 15-53-29

or

Screenshot from 2023-06-08 16-05-15

I don't think that this can be caused by some bug in the checkpointing code, since the checkpointing mechanism doesn't affect the `report_insideoutside` function at all. So what exactly causes this issue? 

I also re-ran the tests on the BCF machine. I did a fresh clone of GAP-C, installed the compiler from scratch and executed all the tests exactly like in the comment above:
```
git clone https://github.com/jlab/gapc.git
git checkout outside_cyk_openMPcheckpoint
./configure && make -j8 && make install
// ran tests (see comment above)
```

Once again, all tests (but one) ran successfully. I created checkpoints in Unger-style + checkpointing, cyk + checkpointing, and cyk + OpenMP + checkpointing programs, both before and after the outside phase for all program variations, restarted the respective programs from those checkpoints and got no diff between the reference output and the output produced by these programs.
The cyk + OpenMP + checkpointing program segfaulted though after restarting it from a checkpoint that was created after 1s,  but not when restarted from a checkpoint that was created later than 1s. That's a new issue that I will have to look into, but in general all tests passed. 

Since I'm still unable to reproduce this issue anywhere, I zipped up the source code and binaries of the Unger-style + checkpointing, cyk + checkpointing, and cyk + OpenMP + checkpointing programs I created on the BCF machine and copied them to  `/vol/jlab/Algorithms/GapcOnSpeed/outside_cyk_cp_programs.zip` in case you want to compare your generated programs with those.

**Pull request merged**
